name: Homegate iOS UI Test
on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: specify Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_13.4.1.app

      - name: install dependencies
        run: |
          npm install
          npm run ios.homegate
