name: Homegate iOS UI Test
on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: specify Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_13.4.1.app/Contents/Developer

      - name: install appium global
        run: |
          npm install -g appium@1.22.3
          appium -v

      - name: install dependencies
        run: npm install
      - name: run test
        run: npm run ios.homegate
